{% set name = "pyscf" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyscf/pyscf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c02deddbed7d1c8f175800eb6ce1bd445cf48c5399b7aefa1c2be3978ecaa023
  patches:
    - upstream-osx.patch
    # https://github.com/pyscf/pyscf/pull/1101
    - upstream-test.patch
    # https://github.com/pyscf/pyscf/pull/1142
    - upstream-linux.patch
    # https://github.com/pyscf/pyscf/pull/1185
    - upstream-test-flaky.patch
    # https://github.com/pyscf/pyscf/pull/990/commits/e09e02e16e9385c2ff96eab2d2d1cf981f1528bb

build:
  number: 0
  skip: true  # [not linux]
  # OSX is skipped because of https://github.com/pyscf/pyscf/issues/1146
  script:
    - export CMAKE_CONFIGURE_ARGS="${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -DBUILD_LIBCINT=OFF -DBUILD_LIBXC=OFF -DBUILD_XCFUN=OFF -LAH"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.10
  host:
    - libblas
    - libcint 4.4.6
    - libxc 5.1.7
    - llvm-openmp
    - make
    - pip
    - python
    - xcfun 2.1.1
  run:
    - h5py >=2.7
    - numpy >=1.13,!=1.16,!=1.17
    - python
    - scipy >=0.19,!=1.5.0,!=1.5
  run_constrained:
    - pyberny >=0.6.2
    - geometric >=0.9.7.2

test:
  imports:
    - pyscf
    - pyscf.dft
    # Tests LIBXC and XCFUN
  commands:
    - pip check
    - .github/workflows/run_tests.sh
  requires:
    - nose
    - nose-cov
    - nose-exclude
    - nose-timer
    - pip
  source_files:
    - .github/workflows/run_tests.sh
    - pyscf

about:
  home: https://pyscf.org
  summary: 'PySCF: Python-based Simulations of Chemistry Framework'
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/pyscf/pyscf

extra:
  recipe-maintainers:
    - BastianZim
