{% set name = "pyscf" %}
{% set version = "2.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyscf/pyscf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f53ea72b25f64cc7a3345b6f1b6e3a30c1cbf550252324731a2192dafe891149
  patches:
    - gh-2482.patch  # test tolerances
    - gh-2458.patch  # libxc 7 support

build:
  number: 0
  skip: true  # [win]
  script:
    - export CMAKE_CONFIGURE_ARGS="${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -DBUILD_LIBCINT=OFF -DBUILD_LIBXC=OFF -DBUILD_XCFUN=OFF -LAH"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
  host:
    - libblas
    - libcint
    - libxc-c >=6,<8
    - llvm-openmp
    - make
    - pip
    - python
    - setuptools
    - xcfun 2.1.1
  run:
    - h5py >=2.7
    - numpy >=1.13,!=1.16,!=1.17
    - python
    - scipy >=0.19,!=1.5.0,!=1.5
    - setuptools
  run_constrained:
    - pyberny >=0.6.2
    - geometric >=0.9.7.2

test:
  imports:
    - pyscf
    - pyscf.dft
    # Tests LIBXC and XCFUN
  commands:
    - pip check
    - cp {{ RECIPE_DIR }}/pyscf_conf.py .pyscf_conf.py
    - >
      pytest pyscf/lib pyscf/scf -s -c pytest.ini --no-cov # Previously this ran: # pytest pyscf/lib pyscf/scf -s -c setup.cfg --cov-report xml --cov-report term --cov-config .coveragerc --cov pyscf # Disabled due to python 3.12.1 memory leak. Should be resolved in python 3.12.2
  requires:
    - pip
    - pytest
    - pytest-cov
  source_files:
    - .coveragerc
    - pyscf
    - pytest.ini

about:
  home: https://pyscf.org
  summary: 'PySCF: Python-based Simulations of Chemistry Framework'
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/pyscf/pyscf

extra:
  recipe-maintainers:
    - awvwgk
    - maxscheurer
    - BastianZim
