{% set name = "pyscf" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyscf/pyscf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 884065031ae6591dbf75cd2e05336bb43363cf44eeef3443de4adefe0124ee36

build:
  number: 0
  skip: true  # [win]
  script:
    - export CMAKE_CONFIGURE_ARGS="${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -DBUILD_LIBCINT=OFF -DBUILD_LIBXC=OFF -DBUILD_XCFUN=OFF -LAH"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - libblas
    - libcint
    - libxc-c >=6
    - llvm-openmp
    - make
    - pip
    - python
    - xcfun 2.1.1
  run:
    - h5py >=2.7
    - numpy >=1.13,!=1.16,!=1.17
    - python
    - scipy >=0.19,!=1.5.0,!=1.5
  run_constrained:
    - pyberny >=0.6.2
    - geometric >=0.9.7.2

test:
  imports:
    - pyscf
    - pyscf.dft
    # Tests LIBXC and XCFUN
  commands:
    - pip check
    - cp {{ RECIPE_DIR }}/pyscf_conf.py .pyscf_conf.py
    - >
      pytest pyscf/lib -s -c setup.cfg --cov-report xml --cov-report term --cov-config .coveragerc --cov pyscf
  requires:
    - pip
    - pytest
    - pytest-cov
  source_files:
    - .coveragerc
    - pyscf
    - setup.cfg

about:
  home: https://pyscf.org
  summary: 'PySCF: Python-based Simulations of Chemistry Framework'
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/pyscf/pyscf

extra:
  recipe-maintainers:
    - awvwgk
    - maxscheurer
    - BastianZim
